// Package turn implements HMAC-SHA1 long-term credential generation and
// validation for the embedded TURN server (RFC 5766 §9.2 / RFC 8489 §9.2).
//
// Credential format (username): "<expiry_unix_seconds>:<room_id>"
// Password: base64( HMAC-SHA1( sharedSecret, username ) )
//
// The server validates credentials by recomputing the HMAC. Credentials are
// time-limited: expiry is embedded in the username itself so the relay can
// reject expired tokens without state.
//
// Invariant: sharedSecret is the relay's POCKETSTATION_JWT_SECRET. No new
// secret surface is introduced.
//
// Phase scope: Phase 5, ADR-023.
// Intentionally not implemented: per-user quota enforcement, IP allow-listing
// (deferred to Phase 6 when multi-region routing lands).
package turn

import (
	"crypto/hmac"
	"crypto/sha1" //nolint:gosec // SHA-1 is required by RFC 5766 §9.2; not used for security-sensitive hashing
	"encoding/base64"
	"fmt"
	"strconv"
	"strings"
	"time"
)

// Credentials generates a time-limited TURN username/password pair for the
// given roomID using secret as the HMAC key.
//
// ttl is the credential validity window. The expiry timestamp is embedded in
// the username so the server can reject expired credentials without storing
// state.
//
// The returned password is base64-encoded HMAC-SHA1(secret, username).
func Credentials(secret []byte, roomID string, ttl time.Duration) (username, password string) {
	expiry := time.Now().Add(ttl).Unix()
	username = fmt.Sprintf("%d:%s", expiry, roomID)
	password = computePassword(secret, username)
	return
}

// Validate checks that password is the correct HMAC-SHA1 credential for
// username and that the embedded expiry has not passed.
//
// Returns false for any malformed or expired credential.
func Validate(secret []byte, username, password string) bool {
	parts := strings.SplitN(username, ":", 2)
	if len(parts) != 2 {
		return false
	}
	expiry, err := strconv.ParseInt(parts[0], 10, 64)
	if err != nil {
		return false
	}
	if time.Now().Unix() > expiry {
		return false
	}
	expected := computePassword(secret, username)
	return hmac.Equal([]byte(password), []byte(expected))
}

// AuthHandler returns a pion/turn AuthHandler that validates HMAC-SHA1
// credentials generated by Credentials.
//
// The handler is called by pion/turn on every STUN ALLOCATE request.
// It returns the raw HMAC bytes that pion/turn uses to verify the client's
// MESSAGE-INTEGRITY attribute per RFC 5389 §10.3.
func AuthHandler(secret []byte) func(username, realm string, _ interface{ String() string }) ([]byte, bool) {
	return func(username, _ string, _ interface{ String() string }) ([]byte, bool) {
		parts := strings.SplitN(username, ":", 2)
		if len(parts) != 2 {
			return nil, false
		}
		expiry, err := strconv.ParseInt(parts[0], 10, 64)
		if err != nil || time.Now().Unix() > expiry {
			return nil, false
		}
		mac := hmac.New(sha1.New, secret) //nolint:gosec
		mac.Write([]byte(username))
		return mac.Sum(nil), true
	}
}

// computePassword returns base64( HMAC-SHA1( secret, username ) ).
func computePassword(secret []byte, username string) string {
	mac := hmac.New(sha1.New, secret) //nolint:gosec
	mac.Write([]byte(username))
	return base64.StdEncoding.EncodeToString(mac.Sum(nil))
}
