// Package turn implements HMAC-SHA1 long-term credential generation and
// validation for the embedded TURN server (RFC 5766 §9.2 / RFC 8489 §9.2).
//
// Credential format (username): "<expiry_unix_seconds>:<room_id>"
// Password: base64( HMAC-SHA1( sharedSecret, username ) )
//
// The server validates credentials by recomputing the HMAC. Credentials are
// time-limited: expiry is embedded in the username itself so the relay can
// reject expired tokens without state.
//
// Invariant: sharedSecret is the dedicated TURN_SHARED_SECRET shared with the
// control plane that issues credentials. It is not a Session JWT secret.
//
// Per-user quotas and IP allow-listing are not implemented.
package turn

import (
	"crypto/hmac"
	"crypto/sha1" //nolint:gosec // SHA-1 is required by RFC 5766 §9.2; not used for security-sensitive hashing
	"encoding/base64"
	"fmt"
	"strconv"
	"strings"
	"time"

	pionTurn "github.com/pion/turn/v4"
)

// Credentials generates a time-limited TURN username/password pair for the
// given roomID using secret as the HMAC key.
//
// ttl is the credential validity window. The expiry timestamp is embedded in
// the username so the server can reject expired credentials without storing
// state.
//
// The returned password is base64-encoded HMAC-SHA1(secret, username).
func Credentials(secret []byte, roomID string, ttl time.Duration) (username, password string) {
	expiry := time.Now().Add(ttl).Unix()
	username = fmt.Sprintf("%d:%s", expiry, roomID)
	password = computePassword(secret, username)
	return
}

// Validate checks that password is the correct HMAC-SHA1 credential for
// username and that the embedded expiry has not passed.
//
// Returns false for any malformed or expired credential.
func Validate(secret []byte, username, password string) bool {
	parts := strings.SplitN(username, ":", 2)
	if len(parts) != 2 {
		return false
	}
	expiry, err := strconv.ParseInt(parts[0], 10, 64)
	if err != nil {
		return false
	}
	if time.Now().Unix() > expiry {
		return false
	}
	expected := computePassword(secret, username)
	return hmac.Equal([]byte(password), []byte(expected))
}

// AuthHandler returns a pion/turn AuthHandler for credentials generated by
// Credentials.
//
// Pion expects the long-term MESSAGE-INTEGRITY key derived from username,
// realm, and password. Returning the REST password bytes directly is invalid
// and causes standards-compliant WebRTC clients to fail TURN allocation.
func AuthHandler(secret []byte) pionTurn.AuthHandler {
	return pionTurn.LongTermTURNRESTAuthHandler(string(secret), nil)
}

// computePassword returns base64( HMAC-SHA1( secret, username ) ).
func computePassword(secret []byte, username string) string {
	mac := hmac.New(sha1.New, secret) //nolint:gosec
	mac.Write([]byte(username))
	return base64.StdEncoding.EncodeToString(mac.Sum(nil))
}
