package clocklineage

import "sync"

const maxTimelinesPerDirection = 8

// Registry bounds Sender Report state to active streams in one PeerConnection.
// Remote timelines describe publisher ingress; local timelines describe relay
// subscriber egress generated by Pion.
type Registry struct {
	mu     sync.Mutex
	remote map[uint32]*Timeline
	local  map[uint32]*Timeline
}

// NewRegistry creates an empty per-PeerConnection registry.
func NewRegistry() *Registry {
	return &Registry{
		remote: make(map[uint32]*Timeline),
		local:  make(map[uint32]*Timeline),
	}
}

// Remote returns stable bounded state for an incoming SSRC.
func (r *Registry) Remote(ssrc uint32) *Timeline { return r.timeline(r.remote, ssrc) }

// Local returns stable bounded state for an outgoing SSRC.
func (r *Registry) Local(ssrc uint32) *Timeline { return r.timeline(r.local, ssrc) }

func (r *Registry) timeline(entries map[uint32]*Timeline, ssrc uint32) *Timeline {
	r.mu.Lock()
	defer r.mu.Unlock()
	if timeline := entries[ssrc]; timeline != nil {
		return timeline
	}
	if len(entries) >= maxTimelinesPerDirection {
		return nil
	}
	timeline := NewTimeline(ssrc)
	entries[ssrc] = timeline
	return timeline
}

func (r *Registry) observeRemote(ssrc uint32) *Timeline { return r.Remote(ssrc) }
func (r *Registry) observeLocal(ssrc uint32) *Timeline  { return r.Local(ssrc) }

func (r *Registry) removeRemote(ssrc uint32) { r.remove(r.remote, ssrc) }
func (r *Registry) removeLocal(ssrc uint32)  { r.remove(r.local, ssrc) }

func (r *Registry) remove(entries map[uint32]*Timeline, ssrc uint32) {
	r.mu.Lock()
	delete(entries, ssrc)
	r.mu.Unlock()
}
